#server:
#  port: 8083

zuul:
  routes:
    sample1:
      path: /sample1/**
      serviceId: sample-service-1
#      url: http://localhost:8081/api
    sample2:
      path: /sample2/**
      serviceId: sample-service-2
#      url: http://localhost:8082/api